config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  resources :page_loads
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page_load.rb
class PageLoad < ApplicationRecord
  scope :per_minute, -> { time_bucket('1 minute') }
  scope :per_hour, -> { time_bucket('1 hour') }
  scope :per_day, -> { time_bucket('1 day') }
  scope :per_week, -> { time_bucket('1 week') }
  scope :per_month, -> { time_bucket('1 month') }
  scope :average_response_time_per_minute, -> { time_bucket('1 minute', value: 'avg(performance)') }
  scope :average_response_time_per_hour, -> { time_bucket('1 hour', value: 'avg(performance)') }
  scope :worst_response_time_last_minute, -> { time_bucket('1 minute', value: 'max(performance)') }
  scope :worst_response_time_last_hour, -> { time_bucket('1 hour', value: 'max(performance)') }
  scope :best_response_time_last_hour, -> { time_bucket('1 hour', value: 'min(performance)') }
  scope :paths, -> { distinct.pluck(:path) }
  scope :time_bucket, -> (time_dimension, value: 'count(1)') {
    select(<<~SQL)
      time_bucket('#{time_dimension}', created_at) as time, path,
      #{value} as value
    SQL
     .group('time, path').order('path, time')
    }

  def self.resume_for(path)
   filter = where(path: path)
   get = -> (scope_name) { filter.send(scope_name).first&.value}
   metrics.each_with_object({}) do |metric, resume|
       resume[metric] = get[metric]
   end
  end

  def self.metrics
    methods.grep /response_time/
  end

  def self.statistics
    paths.each_with_object({}) do |path, resume|
      resume[path] = resume_for(path)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   around_action do |controller, action|
     performance = Benchmark.measure(&action.method(:call))


    PageLoad.create(path: request.path,
      performance: performance.real,
      user_agent: request.user_agent)
   end
end

app/controllers/page_loads_controller.rb
class PageLoadsController < ApplicationController
  before_action :set_page_load, only: %i[ show edit update destroy ]

  # GET /page_loads or /page_loads.json
  def index
    @page_loads = PageLoad.all
  end

  # GET /page_loads/1 or /page_loads/1.json
  def show
  end

  # GET /page_loads/new
  def new
    @page_load = PageLoad.new
  end

  # GET /page_loads/1/edit
  def edit
  end

  # POST /page_loads or /page_loads.json
  def create
    @page_load = PageLoad.new(page_load_params)

    respond_to do |format|
      if @page_load.save
        format.html { redirect_to page_load_url(@page_load), notice: "Page load was successfully created." }
        format.json { render :show, status: :created, location: @page_load }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page_load.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /page_loads/1 or /page_loads/1.json
  def update
    respond_to do |format|
      if @page_load.update(page_load_params)
        format.html { redirect_to page_load_url(@page_load), notice: "Page load was successfully updated." }
        format.json { render :show, status: :ok, location: @page_load }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page_load.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_loads/1 or /page_loads/1.json
  def destroy
    @page_load.destroy

    respond_to do |format|
      format.html { redirect_to page_loads_url, notice: "Page load was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page_load
      @page_load = PageLoad.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_load_params
      params.require(:page_load).permit(:user_agent)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    PageLoad.create(:user_agent => request.user_agent)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_loads_helper.rb
module PageLoadsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimescaleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page_loads/_form.html.erb
<%= form_with(model: page_load) do |form| %>
  <% if page_load.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page_load.errors.count, "error") %> prohibited this page_load from being saved:</h2>

      <ul>
        <% page_load.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_agent, style: "display: block" %>
    <%= form.text_field :user_agent %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/page_loads/_page_load.html.erb
<div id="<%= dom_id page_load %>">
  <p>
    <strong>User agent:</strong>
    <%= page_load.user_agent %>
  </p>

</div>

app/views/page_loads/edit.html.erb
<h1>Editing page load</h1>

<%= render "form", page_load: @page_load %>

<br>

<div>
  <%= link_to "Show this page load", @page_load %> |
  <%= link_to "Back to page loads", page_loads_path %>
</div>

app/views/page_loads/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Page loads</h1>

<div id="page_loads">
  <% @page_loads.each do |page_load| %>
    <%= render page_load %>
    <p>
      <%= link_to "Show this page load", page_load %>
    </p>
  <% end %>
</div>

<%= link_to "New page load", new_page_load_path %>

app/views/page_loads/new.html.erb
<h1>New page load</h1>

<%= render "form", page_load: @page_load %>

<br>

<div>
  <%= link_to "Back to page loads", page_loads_path %>
</div>

app/views/page_loads/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @page_load %>

<div>
  <%= link_to "Edit this page load", edit_page_load_path(@page_load) %> |
  <%= link_to "Back to page loads", page_loads_path %>

  <%= button_to "Destroy this page load", @page_load, method: :delete %>
</div>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<h2>Static Pages requests: <%= PageLoad.count %></h2>
<p>Find me in app/views/static_pages/home.html.erb</p>
<p>Request: <%= @agent %></p>